name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      
      - name: Install Modules
        run: pnpm install

      - name: Run Format
        run: pnpm run format

      - name: Run Lint
        run: pnpm run lint
      
  
